server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 1. 把 /api/search 开头的请求转发给 search-server
    location /api/search {
        include /etc/nginx/snippets/cors.conf;

        proxy_pass http://search-server:8000/;
    }

    # 2. 把 /search-document 开头的请求转发给 search-server
    location /search-document {
        alias /app/search_result/;
    }
}